# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the com.huan.mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said com.huan.mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you com.huan.mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU LGPLv3"
# A URL to refer people to when problems occur with this com.huan.mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual com.huan.mod loader
[[mods]] #mandatory
# The modid of the com.huan.mod
modId="hunger_plus" #mandatory
# The version number of the com.huan.mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the com.huan.mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="1.1.0.0" #mandatory
 # A display name for the com.huan.mod
displayName="Hunger Plus" #mandatory
# A URL to query for updates for this com.huan.mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this com.huan.mod, displayed in the com.huan.mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the com.huan.mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the com.huan.mod UI
credits="焕昭君" #optional
# A text field displayed in the com.huan.mod UI
authors="焕昭君" #optional
# The description text for the com.huan.mod (multi line!) (#mandatory)
description='''
突破原版饥饿值最大上限！可以比原版更大或更小。也提供指令和配置文件。
Breakthrough the maximum limit of vanilla hunger value!Can be larger or smaller than vanilla limit.Also provide commands and configuration files.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.hunger_plus]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.hunger_plus]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"